import Home from '@/components/home/index.component';

export const metadata = {
  title: 'CharmMate',
  description: 'Generated by create next app',
};

export default function HomePage() {
  return <Home />;
}
